# -*- coding: utf-8 -*-
"""FinalFinalQACClean

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z67jGhHE0OWrgsGj-zrU5bUzmoeyxam4

## Google Drive preliminaries
Download files, get URLs, (eventually download entire folders)

### Imports
"""

import pandas as pd
import os

"""### Url paths"""

# google drive URLS
photos_unquantified_folder_url = "https://drive.google.com/drive/folders/11vbDwr9ELMvU02MJ6KjdBRTOqjqMUfrr?usp=drive_link"
photos_quantified_folder_url = "https://drive.google.com/drive/folders/1mpIqMYGkQWq3ij0BOoqebDEj0C7a46NE?usp=drive_link"
test_photo_url_unquantified = "https://drive.google.com/file/d/17eY7TToi9obGM1IaSoRUNYA79eQlKq1C/view?usp=sharing"
test_photo_url_quantified = "https://drive.google.com/file/d/1_lqVr5sqA4f0SKb5m9lmzXJFxCetjJwc/view?usp=sharing"

"""### Test Photo downloads
- The unannotated test image path is unannotated_test_img_path
- The annotate test image path is annotated_test_img_path


"""

def convert_to_uc_link(url):
    import re
    """
    Convert any Google Drive share link into a direct download 'uc?id=' link.
    For:
    - https://drive.google.com/file/d/<ID>/view?usp=sharing
    - https://drive.google.com/open?id=<ID>
    - https://drive.google.com/uc?id=<ID>
    """
    #If already in correct format
    if "uc?id=" in url:
        return url

    #if /file/d/<ID>/view
    match = re.search(r'/file/d/([a-zA-Z0-9_-]+)', url)
    if match:
        file_id = match.group(1)
        return f"https://drive.google.com/uc?id={file_id}"

    #if ?id=<ID>
    match = re.search(r'id=([a-zA-Z0-9_-]+)', url)
    if match:
        file_id = match.group(1)
        return f"https://drive.google.com/uc?id={file_id}"

def download_test_images(photo_url_unquantified, photo_url_quantified, out_dir="demo"):
    """
    Downloads two test images into `out_dir`.

    This is optional helper code for running a small demo locally.
    It requires the `gdown` Python package (not Colab magics).
    """
    import os
    os.makedirs(out_dir, exist_ok=True)

    try:
        import gdown
    except ImportError as e:
        raise ImportError("Missing dependency `gdown`. Install it with: pip install gdown") from e

    # gdown can handle Google Drive share URLs directly when fuzzy=True
    out1 = os.path.join(out_dir, "demo_unannotated.jpg")
    out2 = os.path.join(out_dir, "demo_annotated.jpg")

    gdown.download(photo_url_unquantified, out1, quiet=False, fuzzy=True)
    gdown.download(photo_url_quantified, out2, quiet=False, fuzzy=True)

    return out1, out2


"""## Miscellaneous
Pixel to nano conversion, etc.
"""

def find_pixel_to_nano(path):
  #given an image path, it returns a scalar k st pixel*k = nano meters
  img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
  _, white_image = cv2.threshold(img, 230, 255, cv2.THRESH_BINARY)

  contours, _ = cv2.findContours(white_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


  # k = nano/pixel

  h, w = white_image.shape
  min_x = w
  max_x = 0
  for contour in contours:
    for point in contour:
      x, y = point[0]
      if x < min_x:
        min_x = x
      if x > max_x:
        max_x = x

  return(100/(max_x-min_x))

def invert_nanometer_legend(img):
    #Invert ONLY the pure-white pixels (the scale bar + text) in the image.

    legend_mask = cv2.inRange(img, (220, 220, 220),(255, 255, 255))

    img[legend_mask > 0] = (0, 0, 0)

    return img

"""## Nuclei Detection
Build nuclei masks, annotate nuclei, find the positions and size of each nucleus

### Imports
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import pytesseract

"""### Building First Nuclei Mask
Build first mask by:
- Seperating channels
- Subtracting blue from green to isolate "blueness"
- Using clahe to improve local contrast
- Using Otsu to threshold based on image histogram  

Returns a cv2 image of the first mask
"""

def build_first_mask(impath):
    #Given an image path, return a binary mask of nuclei.
    img = cv2.imread(impath) # import image
    b, g, r = cv2.split(img) # isolate three channels

    blueness = cv2.subtract(b, g) # subtract green from blue to isolate nuclei

    # Use clahe to improve local contrast in  images
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(6, 6))
    blueness_eq = clahe.apply(blueness)


    # Use otsu to threshold the
    otsu_T, _ = cv2.threshold(
      blueness_eq, 0, 255,
      cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )
    # Then I found more success adjusting otsu threshold by a bit
    T = max(1, int(otsu_T - 5))
    _, nuc_mask = cv2.threshold(blueness_eq, T, 255, cv2.THRESH_BINARY)
    return nuc_mask

"""#### Example output"""

def display_example_first_mask(impath):
    #display the first mask side by side with original image
    nuc_mask = build_first_mask(impath)
    fig, ax = plt.subplots(1, 2, figsize=(12, 6))
    img = cv2.imread(impath, 1)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    ax[0].imshow(nuc_mask, cmap = "gray")
    ax[0].set_title("Nuclei Mask")
    ax[1].imshow(img)
    ax[1].set_title("Original Image")
    plt.show()
    return None
# display_example_first_mask(unannotated_test_img_path)

"""### Building Second Nuclei Mask
Build second mask by:
- Run the first mask function
- Use morphology to fill holes and remove noise
- Find the contours to determine the average area of a nuclei
- Erode nuclei based on the average area calculated (larger area, more erosion)

Returns a cv2 image of the second mask
"""

def build_second_mask(impath):

  #Given an image path, return a cleaned and partially separated nuclei mask.

  nuc_mask = build_first_mask(impath)
  kernel = np.ones((2, 2), np.uint8)

  # use morphology to fill holes and remove noise
  nuc_mask_clean = cv2.morphologyEx(nuc_mask, cv2.MORPH_OPEN, kernel, iterations=1)
  nuc_mask_clean = cv2.morphologyEx(nuc_mask_clean, cv2.MORPH_CLOSE, kernel, iterations=1)

  # estimate nucleus size without heavy erosion
  contours0, _ = cv2.findContours(
      nuc_mask_clean, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
  )

  areas0 = np.array([cv2.boundingRect(c)[2] * cv2.boundingRect(c)[3] for c in contours0])
  median_area = np.median(areas0)

  radius_px = (median_area ** 0.5) / 2.0 # treat bbox as ~diameter^2

  # pick erosion iterations based on radius: small for small nuclei, a bit bigger for big ones
  erode_iters = int(max(1, min(3, round(radius_px / 5))))  # between 1 and 3

  # now do the separation erosion with adaptive iters
  nuc_mask_sep = cv2.erode(nuc_mask_clean, kernel, iterations=erode_iters)

  return nuc_mask_sep

"""####Example Output"""

def display_example_second_mask(impath):
    #display the second mask beside the first mask
    nuc_mask = build_first_mask(impath)
    second_nuc_mask = build_second_mask(impath)
    fig, ax = plt.subplots(1, 2, figsize=(12, 6))
    ax[0].imshow(second_nuc_mask, cmap = "gray")
    ax[0].set_title("Second Nuclei Mask")
    ax[1].imshow(nuc_mask, cmap = "gray")
    ax[1].set_title("First Nuclei Mask")
    plt.show()
    return None
# display_example_second_mask(unannotated_test_img_path)

"""### Draw Bounding Circles Around Nuclei
Given an image path, it returns:
- An RGB image with circles around nuclei
- A list of nuclei centers
- A list of nucleus radii  

The function:
- Builds a nuclei mask with build_second_mask
- Finds the contours of the nuclei
- Filters out nuclei which are too small
- Appends the coordinates and radius size of each nuclei to seperate lists

"""

def bounding_boxes_nuc(impath):
    #takes an image path, returns:
    # - an RGB image with circles around nuclei
    # - a list of nucleus centers
    # - a list of nucleus radii

    nuc_mask_sep = build_second_mask(impath)

    contours, _ = cv2.findContours(  # finds contours of nuclei
        nuc_mask_sep, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
    )

    areas = np.array([cv2.boundingRect(c)[2] * cv2.boundingRect(c)[3] for c in contours])
    median_area = np.median(areas)
    min_area = 0.35 * median_area  # disregard nuclei that are too small (likely just noise)

    img = cv2.imread(impath, 1)

    nuc_centers = []
    nuc_radii = []

    for c in contours:
        x, y, w, h = cv2.boundingRect(c)
        area = w * h
        if area > min_area:
            cx = x + w // 2
            cy = y + h // 2
            r = int(0.6 * max(w, h))  # circle radius based on nucleus size

            nuc_centers.append((cx, cy))
            nuc_radii.append(r)

            # draw detection circle
            cv2.circle(img, (cx, cy), r, (0, 0, 255), 2)

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img_rgb, nuc_centers, nuc_radii

"""#### Example Output"""

def display_example_bounding_boxes(impath):
  #display the nuclei-annotated mask next to original image
  nuclei_annotated, _, _ = bounding_boxes_nuc(impath)
  fig, ax = plt.subplots(1, 2, figsize=(12, 6))
  img = cv2.imread(impath, 1)
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  ax[0].imshow(nuclei_annotated)
  ax[0].set_title("Detected Nuclei")
  ax[1].imshow(img)
  ax[1].set_title("Original Image")
  plt.show()
  return None
# display_example_bounding_boxes(unannotated_test_img_path)

"""## Fiber Detection

### Creating a Fiber Mask
Enhance Membranes
- Increase the contrast in the green channel
- Convert to grayscale
- Boost local contrast with clahe  

Return grayscale, "enhanced" image

Get Fiber Mask
- Use enhance membranes function
- Otsu threshold on enhanced image
- Invert color
- Erode so fibers dont touch eachother
- Use distance transform to only threshold pixels closer to the center of the fiber  

Return the fiber mask image

#### Enhance Membranes and Example Output
"""

def enhance_membranes(img, alpha=0.5, beta=0.2):
    #given an image, it returns an "enhanced" image where:
    # noisier channels are subtracted
    # local contrast is increased with clahe
    b, g, r = cv2.split(img)

    #subtract b and r channels in various quantities
    enhanced = g.astype(np.float32) - alpha*b.astype(np.float32) - beta*r.astype(np.float32)
    enhanced = np.clip(enhanced, 0, 255).astype(np.uint8)

    #use clahe to boost local contrast in a 8x8 sized square
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    enhanced = clahe.apply(enhanced)

    return enhanced

def show_enhanced_example(path, alpha=0.3, beta=0.2):
    #Display the original image next to the enhanced membrane image.
    img = cv2.imread(path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    enhanced = enhance_membranes(img, alpha=alpha, beta=beta)
    fig, ax = plt.subplots(1, 2, figsize=(12, 6))
    ax[0].imshow(enhanced, cmap="gray")
    ax[0].set_title("Enhanced Membrane Image")
    ax[1].imshow(img_rgb)
    ax[1].set_title("Original Image")
    plt.show()
    return None

# show_enhanced_example(unannotated_test_img_path)

"""#### Fiber Mask and Example Outbput"""

def get_fiber_mask(path):
    img = cv2.imread(path)

    #invert nanometer legend
    img = invert_nanometer_legend(img)

    # boost membrane contrast (green) so fibers stand out
    enhanced = enhance_membranes(img, alpha=0.3)

    # smooth noise a bit
    blur = cv2.GaussianBlur(enhanced, (5,5), 0)


    # threshold to get membrane vs interior
    _, mem = cv2.threshold(blur, 0, 255,
                           cv2.THRESH_BINARY + cv2.THRESH_OTSU)

    # flip so fiber interiors are white
    interior = 255 - mem

    # shrink interiors so fibers don’t touch each other
    small_k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3,3))
    interior = cv2.morphologyEx(interior, cv2.MORPH_ERODE, small_k, iterations=2)

    # distance map = how deep inside a fiber each pixel is
    dist = cv2.distanceTransform(interior, cv2.DIST_L2, 5)
    dist_norm = cv2.normalize(dist, None, 0, 255,
                              cv2.NORM_MINMAX).astype(np.uint8)

    # pick pixels “deep enough” → becomes our fiber mask
    _, fiber_mask = cv2.threshold(dist_norm, 25, 255,
                                  cv2.THRESH_BINARY)

    # clean up shape (fill holes)
    k_close = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,5))
    fiber_mask = cv2.morphologyEx(fiber_mask, cv2.MORPH_CLOSE, k_close, iterations=1)

    # remove tiny specks
    k_open = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3,3))
    fiber_mask = cv2.morphologyEx(fiber_mask, cv2.MORPH_OPEN, k_open, iterations=1)

    # push mask outward closer to actual membrane
    k_dilate = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,5))
    fiber_mask = cv2.dilate(fiber_mask, k_dilate, iterations=2)

    return fiber_mask

def show_fiber_mask_example(path):
    #Display the original image next to the enhanced membrane image.
    img = cv2.imread(path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    fiber_mask = get_fiber_mask(path)
    fig, ax = plt.subplots(1, 2, figsize=(12, 6))
    ax[0].imshow(fiber_mask, cmap="gray")
    ax[0].set_title("Fiber Mask Image")
    ax[1].imshow(img_rgb)
    ax[1].set_title("Original Image")
    plt.show()
    return None

# show_fiber_mask_example(unannotated_test_img_path)

"""### Check Fiber Distance and Get Fiber Candidates

#### Get contour distance (for fibers)
- First use the center of the fiber to rule out fibers which are far away using contours_too_close
- Then if two fibers' centers are sufficiently close, then use contour_min_distance to find the exact distance between the two fibers
- (contour_min_distance will also be useful for detecting nearby nuclei)
"""

def boxes_touch(b1, b2, margin=15):
    x1, y1, w1, h1 = b1
    x2, y2, w2, h2 = b2
    return (x1 < x2 + w2 + margin and
            x1 + w1 + margin > x2 and
            y1 < y2 + h2 + margin and
            y1 + h1 + margin > y2)

def contour_min_distance(c1, c2):

    #Return the minimum  distance between two contours c1 and c2.
    #c1 and c2 are arrays of shape (N, 1, 2) as returned by findContours.

    min_dist = float("inf")
    for p1 in c1:
        for p2 in c2:
            dx = p1[0][0] - p2[0][0]
            dy = p1[0][1] - p2[0][1]
            d2 = dx*dx + dy*dy
            if d2 < min_dist:
                min_dist = d2
    return np.sqrt(min_dist)


def contours_too_close(cnt, bbox, other_cnt, other_bbox, min_dist):
    #Return True if two contours are closer than min_dist pixels.
    #Uses bounding boxes to pre filter

    if not boxes_touch(bbox, other_bbox, margin=min_dist):
        return False

    # if boxes are near each other, check precise contour distance
    return contour_min_distance(cnt, other_cnt) < min_dist

def get_fiber_candidates(path):

    mask = get_fiber_mask(path)

    min_area = 600
    max_area = 1_000_000
    min_circularity = 0.1
    border_margin = 1
    min_contour_dist = 100   # non adjacent

    h, w = mask.shape

    contours, _ = cv2.findContours(
        mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE
    )

    fibers = []

    for cnt in contours:
        area = cv2.contourArea(cnt)
        if not (min_area < area < max_area):
            continue

        x, y, ww, hh = cv2.boundingRect(cnt)
        bbox = (x, y, ww, hh)

        # border rejection
        if x < border_margin or y < border_margin or \
           x+ww > w-border_margin or y+hh > h-border_margin:
            continue

        # perimeter
        peri = cv2.arcLength(cnt, True)
        if peri == 0:
            continue

        # circularity
        circularity = 4*np.pi*area/(peri**2)
        if circularity < min_circularity:
            continue

        # centroid
        M = cv2.moments(cnt)
        cx = M["m10"]/M["m00"]
        cy = M["m01"]/M["m00"]

        # adjacency filters using contour distance
        too_close = False
        for f in fibers:
            if contours_too_close(
                cnt, bbox,
                f["contour"], f["bbox"],
                min_dist=min_contour_dist
            ):
                too_close = True
                break

        if too_close:
            continue

        fibers.append({
            "contour": cnt,
            "centroid": (cx, cy),
            "area": area,
            "perimeter": peri,
            "circularity": circularity,
            "bbox": bbox
        })

    return fibers

"""#### Get Fiber Candadites Function and Example Output
Given an image path, it returns an array of fibers, where each fiber contains its position (contour) and a variety of measurements. Works by:
- Getting fiber mask
- Finding contours
- Excluding contours with area that are extreme outliers
- Excludes contours too close to the border
- Excludes contours which are not sufficiently round
- Removes fibers which are too close to eachother

"""

def show_fiber_candidates(path):
    #Display the original image next to an annotated version
    #showing detected fiber candidates (contours + centroids)
    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    annotated = img.copy()

    fibers = get_fiber_candidates(path)

    #draw contours + centroids
    for f in fibers:
        cnt = f["contour"]
        cx, cy = f["centroid"]

        cv2.drawContours(annotated,[cnt],-1,(255, 255, 0),  2)

        #draw centroid
        cv2.circle(annotated,(int(cx), int(cy)),4,(255, 0, 0), -1)
    fig, ax = plt.subplots(1, 2, figsize=(14, 7))
    ax[0].imshow(annotated)
    ax[0].set_title("Detected Fiber Candidates")
    ax[1].imshow(img)
    ax[1].set_title("Original Image")
    plt.show()
    return None
# show_fiber_candidates(unannotated_test_img_path)

"""## Computing Fiber Metrics"""

def compute_fiber_metrics(path, fibers, use_existing_index=False):
    """
    Given:
      - path: image path
      - fibers: list of fiber dicts produced by get_fiber_candidates()
      - use_existing_index: if True and fiber["index"] exists, use that
        as Fiber ID instead of 1 to N

    Returns a list of dicts, one per fiber, with keys:
      - fiber_id
      - centroid
      - area_px
      - CSA
      - nuclei_count
      - nuclei_indices (indices into the global nuclei list)
      - contour (original, non-expanded contour)
    """

    dilate_kernel_size = (20, 20)
    dilate_iters = 2
    dist_limit = 40  # how far in px from expanded contour a nucleus can be

    #load dimensions of image (for mask)
    base_img = cv2.imread(path, cv2.IMREAD_COLOR)
    h, w = base_img.shape[:2]

    #nuclei detection
    _, nuc_centers, nuc_radii = bounding_boxes_nuc(path)

    #kernel for expanding contours
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, dilate_kernel_size)

    #area conversions for CSA
    px_to_unit = find_pixel_to_nano(path)
    area_scale = px_to_unit ** 2

    fiber_metrics = []

    for idx, f in enumerate(fibers, start=1):
        cnt = f["contour"]
        cx, cy = f["centroid"]
        area_px = f.get("area", cv2.contourArea(cnt))

        #fiber_id is either preassigned (if for training) or just 1 to N
        if use_existing_index and ("index" in f) and (f["index"] is not None):
            fiber_id = int(f["index"])
        else:
            fiber_id = idx

        # build expanded contour mask (to find attached nuclei)
        temp = np.zeros((h, w), dtype=np.uint8)
        cv2.drawContours(temp, [cnt], -1, 255, 1)
        temp = cv2.dilate(temp, kernel, iterations=dilate_iters)

        new_cnts, _ = cv2.findContours(temp, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        exp_cnt = new_cnts[0] if new_cnts else cnt

        # assign nuclei to this fiber using distance to expanded contour
        nuclei_indices = []
        for n_idx, ((nx, ny), r) in enumerate(zip(nuc_centers, nuc_radii)):
            d = cv2.pointPolygonTest(exp_cnt, (float(nx), float(ny)), True)
            if d >= -dist_limit:
                nuclei_indices.append(n_idx)

        csa = area_px * area_scale

        fiber_metrics.append({
            "fiber_id": fiber_id,
            "centroid": (cx, cy),
            "area_px": area_px,
            "CSA": csa,
            "nuclei_count": len(nuclei_indices),
            "nuclei_indices": nuclei_indices,
            "contour": cnt
        })

    return fiber_metrics

"""### Example output"""

def draw_fibers_and_nuclei_annotated(
    path,
    fibers=None,
    use_existing_index=False
):
    """
    Given an image path, draw:

      - expanded fiber outlines in yellow
      - fiber IDs at centroids
      - attached nuclei as yellow circles with per-fiber nucleus IDs

    Returns:
      annotated RGB image (numpy array).
    """
    dilate_kernel_size=(20, 20)
    dilate_iters=2
    dist_limit=40

    base_bgr = cv2.imread(path)
    base_img = cv2.cvtColor(base_bgr, cv2.COLOR_BGR2RGB)
    annotated = base_img.copy()

    # use same nuclei + kernel settings as compute_fiber_metrics
    _, nuc_centers, nuc_radii = bounding_boxes_nuc(path)
    h, w = annotated.shape[:2]
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, dilate_kernel_size)

    if fibers is None:
        fibers = get_fiber_candidates(path)

    font = cv2.FONT_HERSHEY_SIMPLEX

    for idx, f in enumerate(fibers, start=1):
        cnt = f["contour"]
        cx, cy = f["centroid"]

        if use_existing_index and ("index" in f) and (f["index"] is not None):
            fiber_id = int(f["index"])
        else:
            fiber_id = idx

        # expand contour
        temp = np.zeros((h, w), dtype=np.uint8)
        cv2.drawContours(temp, [cnt], -1, 255, 1)
        temp = cv2.dilate(temp, kernel, iterations=dilate_iters)
        new_cnts, _ = cv2.findContours(temp, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        exp_cnt = new_cnts[0] if new_cnts else cnt

        # draw expanded contour + fiber ID
        cv2.drawContours(annotated, [exp_cnt], -1, (255, 255, 0), 2)
        cv2.putText(annotated,str(fiber_id),(int(cx) - 10, int(cy) - 10),font,0.9,(255, 255, 0),2)

        # label nuclei for this fiber
        nucleus_counter = 1
        for (nx, ny), r in zip(nuc_centers, nuc_radii):
            d = cv2.pointPolygonTest(exp_cnt, (float(nx), float(ny)), True)
            if d >= -dist_limit:
                cv2.circle(annotated, (nx, ny), int(r * 1.4), (255, 255, 0), 2)
                cv2.putText(annotated,str(nucleus_counter),(nx + 10, ny - 10),font,0.7,(255, 255, 0),2)
                nucleus_counter += 1
    return annotated
#plt.imshow(draw_fibers_and_nuclei_annotated(unannotated_test_img_path))

"""## Forcing fiber selection choice
For evaluation

### Find fiber indices
The lab indexes the fibers with small numbers written inside each fiber. To evaluate, we must pick the same choice of fiber

#### Get fiber mask and example output
"""

def get_index_mask(path, show_debug=False):
    img = cv2.imread(path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Detect pixels where R,G,B are almost equal (gray-ish text)
    R = img_rgb[:,:,0].astype(np.int16)
    G = img_rgb[:,:,1].astype(np.int16)
    B = img_rgb[:,:,2].astype(np.int16)

    t = 12  # threshold for RGB similarity

    eq_mask = (
        (np.abs(R - G) < t) &
        (np.abs(G - B) < t) &
        (np.abs(R - B) < t)
    )

    # Preserve original brightness of the pixel
    gray = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)
    idx_mask = np.zeros_like(gray)
    idx_mask[eq_mask] = gray[eq_mask]

    # Debug display (ONLY the first image)
    if show_debug:
        plt.figure(figsize=(20,20))
        plt.imshow(idx_mask, cmap="gray")
        plt.title("Gray-ish pixels (brightness preserved)")
        plt.axis("off")
        plt.show()

    return idx_mask

#Example output
#idx_mask = get_index_mask(annotated_test_img_path, show_debug=False)

"""####OCR on Mask for indexes"""

def ocr_single_digit(idx_mask, centroid, radius=60):
    cx, cy = int(centroid[0]), int(centroid[1])
    H, W = idx_mask.shape

    # crop circular ROI
    x1, y1 = max(0, cx - radius), max(0, cy - radius)
    x2, y2 = min(W, cx + radius), min(H, cy + radius)

    roi = idx_mask[y1:y2, x1:x2]

    # upscale for OCR
    up = cv2.resize(roi, None, fx=4, fy=4, interpolation=cv2.INTER_LINEAR)

    # threshold
    _, bw = cv2.threshold(up, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

    # invert if needed
    if np.mean(bw) < 127:
        bw = 255 - bw

    # OCR config
    config = "--psm 10 -c tessedit_char_whitelist=0123456789"
    text = pytesseract.image_to_string(bw, config=config).strip()

    return int(text) if text.isdigit() else None

"""#### Get fibers from quantified image and example output"""

def extract_gt_fibers_from_quantified_image(path, show_mask=False, idx_mask=None, ocr_radius=60):
    img = cv2.imread(path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # --- detect yellow outlines ---
    hsv = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2HSV)
    lower_yellow = np.array([20, 40, 40])
    upper_yellow = np.array([50, 255, 255])

    yellow_mask = cv2.inRange(hsv, lower_yellow, upper_yellow)

    # thicken + close gaps
    k1 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,5))
    yellow_mask = cv2.dilate(yellow_mask, k1, iterations=3)

    k2 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (9,9))
    yellow_mask = cv2.morphologyEx(yellow_mask, cv2.MORPH_CLOSE, k2, iterations=2)

    cnts, _ = cv2.findContours(yellow_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    training_fibers = []

    for cnt in cnts:
        if cv2.contourArea(cnt) < 500:
            continue

        M = cv2.moments(cnt)
        if M["m00"] == 0:
            continue

        cx = M["m10"] / M["m00"]
        cy = M["m01"] / M["m00"]

        # --- OCR ---
        idx = ocr_single_digit(idx_mask, (cx, cy), radius=ocr_radius) if idx_mask is not None else None

        training_fibers.append({
            "contour": cnt,
            "centroid": (cx, cy),
            "area": cv2.contourArea(cnt),
            "index": idx
        })

    if show_mask:
        return training_fibers, yellow_mask, img_rgb
    return training_fibers

#Example output
def visualize_training_fibers(img_rgb, training_fibers):
    vis = cv2.cvtColor(img_rgb.copy(), cv2.COLOR_RGB2BGR)

    for f in training_fibers:
        cnt = f["contour"]
        cx, cy = int(f["centroid"][0]), int(f["centroid"][1])
        idx = f["index"]

        # yellow outline
        cv2.drawContours(vis, [cnt], -1, (0,255,255), 3)

        # red centroid
        cv2.circle(vis, (cx, cy), 10, (0,0,255), -1)

        # green OCR index
        cv2.putText(
            vis,
            str(idx) if idx is not None else "?",
            (cx + 15, cy - 15),
            cv2.FONT_HERSHEY_SIMPLEX,
            2.0,
            (0,255,0) if idx is not None else (0,0,255),
            4,
            cv2.LINE_AA
        )

    vis_rgb = cv2.cvtColor(vis, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(15,15))
    plt.imshow(vis_rgb)
    plt.title("Training Fibers with OCR Index Labels")
    plt.axis("off")
    plt.show()

    return vis_rgb
'''
training_fibers, yellow_mask, img_rgb = extract_gt_fibers_from_quantified_image(
    show_mask=True
    idx_mask=idx_mask=
)
plt.imshow(yellow_mask, cmap="gray")
'''

"""### Find matched fibers on unannotated image"""

def find_fiber_candidates_matched(path, gt_training_fibers):
    """
    Detect fibers on the unannotated image using get_fiber_candidates(),
    then match each GT fiber to the nearest unused detected fiber
    by centroid distance.

    Returns a list of dicts with keys:
    contour, centroid, area, index, nuclei_count
    """

    # nuclei detection once
    _, nuc_centers, nuc_radii = bounding_boxes_nuc(path)

    # detect fibers
    auto_fibers = get_fiber_candidates(path)


    base_img = cv2.imread(path, cv2.IMREAD_COLOR)
    h, w = base_img.shape[:2]

    dilate_kernel_size = (20, 20)
    dilate_iters = 2
    dist_limit = 40

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, dilate_kernel_size)

    used = set()
    matched = []

    for gt in gt_training_fibers:
        gx, gy = gt["centroid"]
        gt_index = gt.get("index", None)

        # find nearest unused auto fiber
        best_j = None
        best_d = float("inf")

        for j, af in enumerate(auto_fibers):
            if j in used:
                continue
            ax, ay = af["centroid"]
            d = (ax - gx) ** 2 + (ay - gy) ** 2
            if d < best_d:
                best_d = d
                best_j = j

        if best_j is None:
            continue

        used.add(best_j)
        af = auto_fibers[best_j]
        cnt = af["contour"]

        # build expanded contour
        temp = np.zeros((h, w), dtype=np.uint8)
        cv2.drawContours(temp, [cnt], -1, 255, 1)
        temp = cv2.dilate(temp, kernel, iterations=dilate_iters)

        new_cnts, _ = cv2.findContours(temp, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        exp_cnt = new_cnts[0] if new_cnts else cnt

        # count nuclei attached to this fiber
        myon = 0
        for (nx, ny), r in zip(nuc_centers, nuc_radii):
            d = cv2.pointPolygonTest(exp_cnt, (float(nx), float(ny)), True)
            if d >= -dist_limit:
                myon += 1

        matched.append({
            "contour": cnt,
            "centroid": af["centroid"],
            "area": af.get("area", cv2.contourArea(cnt)),
            "index": gt_index,
            "nuclei_count": myon
        })

    return matched

#example output
def draw_matched_fibers(path, fibers):
    img = cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)

    for f in fibers:
        cnt = f["contour"]
        cx, cy = map(int, f["centroid"])
        idx = f["index"]

        cv2.drawContours(img, [cnt], -1, (255,255,0), 2)
        cv2.putText(img, str(idx), (cx, cy),
                    cv2.FONT_HERSHEY_SIMPLEX, 1.2, (255,0,0), 3)

    plt.figure(figsize=(12,12))
    plt.imshow(img)
    plt.axis("off")
    plt.show()

    return img

#matched_fibers = find_fiber_candidates_matched(unannotated_test_img_path, training_fibers)

#vis = draw_matched_fibers(unannotated_test_img_path, matched_fibers)

"""### Wrap into one function"""

def get_matched_fibers(annotated_path, unannotated_path, show_mask=False):
    """
    Combines index-mask extraction, training fiber extraction,
    and matching into ONE function.
    """

    # 1) Get index mask
    idx_mask = get_index_mask(annotated_path, show_debug=False)

    # 2) Extract training fibers (returns FOUR values)
    training_fibers= extract_gt_fibers_from_quantified_image(
        annotated_path,
        show_mask=False,
        idx_mask=idx_mask
    )

    # 3) Match fibers
    matched_fibers = find_fiber_candidates_matched(
        unannotated_path,
        training_fibers
    )

    return matched_fibers

"""## Dataframe Logic"""

def parse_filename_metadata(image_path):
    """
    Parse SqID, State, Muscle, Slide, Section from a filename like:
        '240305_MIDHIB_GASTRO_A1_Sect2_0001 2.jpg'

    Assumes pattern:
        SqID_State_Muscle_Slide_Section_...
    """
    fname = os.path.basename(image_path)

    #we made a copy of the images to make the sharing permissions public for !gdown
    #But this line is harmless if the image doesn't contain "Copy of " anyway
    fname = fname.replace("Copy of ", '')
    root, _ = os.path.splitext(fname)

    parts = root.split("_")

    SqID   = parts[0]
    State  = parts[1]
    Muscle = parts[2].upper()
    Slide  = parts[3]
    Section = parts[4]

    return SqID, State, Muscle, Slide, Section

def fiber_metrics_dataframe(path, fibers, use_existing_index=False):
    """
    For a single image, return a DataFrame with:
      SqID, State, Muscle, Slide, Section, Fiber Number, CSA, MyoN
    """
    SqID, State, Muscle, Slide, Section = parse_filename_metadata(path)
    metrics = compute_fiber_metrics(path, fibers=fibers, use_existing_index=use_existing_index)

    rows = []
    for m in metrics:
        rows.append({
            "SqID": SqID,
            "State": State,
            "Muscle": Muscle,
            "Slide": Slide,
            "Section": Section,
            "Fiber Number": m["fiber_id"],
            "CSA": m["CSA"],
            "MyoN": m["nuclei_count"],
        })

    df = pd.DataFrame(rows).sort_values("Fiber Number").reset_index(drop=True)
    return df

"""#### Example Output"""

#fdf = fiber_metrics_dataframe(unannotated_test_img_path, get_fiber_candidates(unannotated_test_img_path))

# fdf

"""## Download / Process folders with ALL images

Note as a preliminary, __you MUST have QAC_Final_Quantified.zip and QAC_Final_Unquantified.zip downloaded__ into your colab (gdown didnt work with these massive folders)

### Imports and helpers
"""

import os
import shutil
import zipfile
import pandas as pd

def unzip_to(zip_path, out_dir):
    with zipfile.ZipFile(zip_path, "r") as z:
        z.extractall(out_dir)

def wipe_dir(d):
    if os.path.exists(d):
        shutil.rmtree(d)
    os.makedirs(d, exist_ok=True)

def collect_image_paths(root_dir, exts=(".jpg",".jpeg",".png",".tif",".tiff")):
    paths = []
    for r, _, fnames in os.walk(root_dir):
        for f in fnames:
            if f.lower().endswith(exts):
                paths.append(os.path.join(r, f))
    return paths

def build_basename_map(paths):
    """
    Returns a mapping of basename -> full path (first occurrence wins),
    and a list of dupes (if they exist)
    """
    mapping = {}
    dupes = []

    for p in paths:
        b = os.path.basename(p)
        if b in mapping:
            dupes.append(b)
        else:
            mapping[b] = p

    return mapping, dupes

def find_raw_for_quantified(qname, raw_files):
    """
    Match a quantified filename to its corresponding raw filename.

    Handles common prefixes produced by Drive/Finder:
      - "Quantified "
      - "Copy of Quantified "
      - "Copy of "
      - "Copy "

    Also tolerates leading junk like "-_", "_-", "-", "_", or spaces.
    """
    q = qname.lower().strip()

    # strip leading junk that sometimes appears in filenames
    q = q.lstrip(" _-")

    # strip common prefixes 
    prefixes = [
        "copy of quantified",
        "quantified",
        "copy of",
        "copy",
    ]
    for p in prefixes:
        if q.startswith(p):
            q = q[len(p):].strip()
            q = q.lstrip(" _-")  # in case something like "-_Quantified ..."
            break

    q_no_ext = os.path.splitext(q)[0]

    # build a lookup for exact basename matches (fast + reliable)
    raw_map = {os.path.splitext(r.lower().strip())[0]: r for r in raw_files}

    # exact match
    if q_no_ext in raw_map:
        return raw_map[q_no_ext]

    # fallback: substring match 
    for r in raw_files:
        r_no_ext = os.path.splitext(r.lower().strip())[0]
        if q_no_ext in r_no_ext:
            return r

    return None


"""### Run everything
NOTE on the full dataset this will probably take like an hour and a half
"""

def run_final_from_local_zips(
    quantified_zip=None,
    unquantified_zip=None,
    quantified_dir="data/quantified",
    unquantified_dir="data/unquantified",
    exts=(".jpg",".jpeg",".png",".tif",".tiff"),
    n=None # number of image pairs to process (takes around 40 seconds per pair)
    # full data set would take like an hour and a half
):
    # check zips exist
    if not os.path.exists(quantified_zip):
        raise FileNotFoundError(f"Missing quantified zip: {quantified_zip}")
    if not os.path.exists(unquantified_zip):
        raise FileNotFoundError(f"Missing unquantified zip: {unquantified_zip}")

    print("Found zip files.")

    # Reset folders
    wipe_dir(quantified_dir)
    wipe_dir(unquantified_dir)

    # Unzip
    unzip_to(quantified_zip, quantified_dir)
    unzip_to(unquantified_zip, unquantified_dir)

    # Collect images
    q_paths = collect_image_paths(quantified_dir, exts)
    r_paths = collect_image_paths(unquantified_dir, exts)

    print("Extracted image counts:")
    print("  quantified:", len(q_paths))
    print("  unquantified:", len(r_paths))

    # Build maps
    q_map, q_dupes = build_basename_map(q_paths)
    r_map, r_dupes = build_basename_map(r_paths)

    if q_dupes:
        print("Duplicate quantified filenames:", q_dupes[:10])
    if r_dupes:
        print("Duplicate unquantified filenames:", r_dupes[:10])

    # Process
    all_dfs = []
    unmatched = []
    errors = []

    processed_pairs = 0

    out_dir = "outputs"
    os.makedirs(out_dir, exist_ok=True)


    for qname in q_map:
        raw_name = find_raw_for_quantified(qname, list(r_map.keys()))
        if raw_name is None or raw_name not in r_map:
            unmatched.append(qname)
            print(f"No raw match for quantified: {qname}")
            continue

        if n is not None and processed_pairs >= n:
            break

        annotated_path = q_map[qname]
        unannotated_path = r_map[raw_name]

        print(f"\nProcessing pair:\n  Raw: {raw_name}\n  Annotated: {qname}")

        try:
            matched_fibers = get_matched_fibers(annotated_path, unannotated_path)

            annotated_vis = draw_fibers_and_nuclei_annotated(
                unannotated_path,
                matched_fibers,
                use_existing_index=True
            )

            base = os.path.splitext(os.path.basename(unannotated_path))[0]
            out_path = os.path.join(out_dir, f"annotated_{base}.png")

            cv2.imwrite(
                out_path,
                cv2.cvtColor(annotated_vis, cv2.COLOR_RGB2BGR)
            )

            df = fiber_metrics_dataframe(unannotated_path, matched_fibers, True)
            df["source_image"] = raw_name
            df["quantified_image"] = qname
            all_dfs.append(df)

            processed_pairs += 1

        
        except Exception as e:
            errors.append((raw_name, qname, str(e)))
            print(f"Error processing raw={raw_name}: {e}")

    if not all_dfs:
        raise RuntimeError("No objects to concatenate.")

    final_df = pd.concat(all_dfs, ignore_index=True)

    print("\nDone.")
    print("  processed pairs:", len(all_dfs))
    print("  unmatched quantified:", len(unmatched))
    print("  errors:", len(errors))

    return final_df, unmatched, errors

"""### Accuracy metrics

"""

def evaluate_fiber_pipeline(final_df, squirrel_df, verbose=True):
    """
    Compare predicted fiber metrics (final_df) against ground truth (squirrel_df).
    """

    import numpy as np
    import pandas as pd
    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

    pred = final_df.copy()
    gt = squirrel_df.copy()

    # Normalize merge keys
    def normalize_section(x):
        if pd.isna(x):
            return None
        return "".join(c for c in str(x) if c.isdigit())

    for df in (pred, gt):
        df["SqID"] = df["SqID"].astype(str)
        df["Muscle"] = df["Muscle"].astype(str)
        df["Section"] = df["Section"].apply(normalize_section)
        df["Fiber Number"] = df["Fiber Number"].astype(int)

    pred = pred.rename(columns={"CSA": "CSA_pred", "MyoN": "MyoN_pred"})
    gt = gt.rename(columns={"CSA": "CSA_gt", "MyoN": "MyoN_gt"})

    results = {}

    # Fiber-level evaluation
    fiber_eval = pd.merge(
        pred,
        gt,
        on=["SqID", "Muscle", "Section", "Fiber Number"],
        how="inner"
    )

    results["coverage"] = {
        "pred_fibers": len(pred),
        "gt_fibers": len(gt),
        "matched_fibers": len(fiber_eval),
        "fiber_match_rate": len(fiber_eval) / max(len(gt), 1)
    }

    if len(fiber_eval) > 0:
        results["fiber_metrics"] = {
            "CSA_MAE": mean_absolute_error(fiber_eval["CSA_gt"], fiber_eval["CSA_pred"]),
            "CSA_RMSE": np.sqrt(mean_squared_error(
                fiber_eval["CSA_gt"], fiber_eval["CSA_pred"]
            )),
            "CSA_R2": r2_score(fiber_eval["CSA_gt"], fiber_eval["CSA_pred"]),
            "MyoN_MAE": mean_absolute_error(
                fiber_eval["MyoN_gt"], fiber_eval["MyoN_pred"]
            ),
            "MyoN_RMSE": np.sqrt(mean_squared_error(
                fiber_eval["MyoN_gt"], fiber_eval["MyoN_pred"]
            )),
            "MyoN_Exact_Accuracy": np.mean(
                fiber_eval["MyoN_gt"] == fiber_eval["MyoN_pred"]
            )
        }
    else:
        results["fiber_metrics"] = None

    # Section-level evaluation
    pred_sec = (
        pred
        .groupby(["SqID", "Muscle", "Section"])
        .agg(
            CSA_pred_mean=("CSA_pred", "mean"),
            CSA_pred_sum=("CSA_pred", "sum"),
            MyoN_pred_sum=("MyoN_pred", "sum"),
            n_fibers_pred=("Fiber Number", "count")
        )
        .reset_index()
    )

    gt_sec = (
        gt
        .groupby(["SqID", "Muscle", "Section"])
        .agg(
            CSA_gt_mean=("CSA_gt", "mean"),
            CSA_gt_sum=("CSA_gt", "sum"),
            MyoN_gt_sum=("MyoN_gt", "sum"),
            n_fibers_gt=("Fiber Number", "count")
        )
        .reset_index()
    )

    sec_eval = pd.merge(
        pred_sec,
        gt_sec,
        on=["SqID", "Muscle", "Section"],
        how="inner"
    )

    if len(sec_eval) > 0:
        results["section_metrics"] = {
            "CSA_mean_MAE": mean_absolute_error(
                sec_eval["CSA_gt_mean"], sec_eval["CSA_pred_mean"]
            ),
            "CSA_sum_MAE": mean_absolute_error(
                sec_eval["CSA_gt_sum"], sec_eval["CSA_pred_sum"]
            ),
            "MyoN_sum_MAE": mean_absolute_error(
                sec_eval["MyoN_gt_sum"], sec_eval["MyoN_pred_sum"]
            ),
            "Fiber_count_MAE": mean_absolute_error(
                sec_eval["n_fibers_gt"], sec_eval["n_fibers_pred"]
            ),
            "n_sections_evaluated": len(sec_eval)
        }
    else:
        results["section_metrics"] = None

    # Print summary
    if verbose:
        print("\n=== Coverage ===")
        print(f"pred_fibers        : {results['coverage']['pred_fibers']}")
        print(f"gt_fibers          : {results['coverage']['gt_fibers']}")
        print(f"matched_fibers     : {results['coverage']['matched_fibers']}")
        print(f"fiber_match_rate   : {results['coverage']['fiber_match_rate']:.4f}")

        print("\n=== Fiber-level metrics ===")
        fm = results["fiber_metrics"]
        if fm is None:
            print("No matched fibers")
        else:
            print(f"CSA_MAE            : {float(fm['CSA_MAE']):.2f}")
            print(f"CSA_RMSE           : {float(fm['CSA_RMSE']):.2f}")
            print(f"CSA_R2             : {float(fm['CSA_R2']):.3f}")
            print(f"MyoN_MAE           : {float(fm['MyoN_MAE']):.2f}")
            print(f"MyoN_RMSE          : {float(fm['MyoN_RMSE']):.2f}")
            print(f"MyoN_Exact_Acc     : {float(fm['MyoN_Exact_Accuracy']):.3f}")

        print("\n=== Section-level metrics ===")
        sm = results["section_metrics"]
        if sm is None:
            print("No matched sections")
        else:
            print(f"CSA_mean_MAE       : {float(sm['CSA_mean_MAE']):.2f}")
            print(f"CSA_sum_MAE        : {float(sm['CSA_sum_MAE']):.2f}")
            print(f"MyoN_sum_MAE       : {float(sm['MyoN_sum_MAE']):.2f}")
            print(f"Fiber_count_MAE    : {float(sm['Fiber_count_MAE']):.2f}")
            print(f"n_sections_eval    : {sm['n_sections_evaluated']}")

    return results

if __name__ == "__main__":
    import argparse
    import os

    parser = argparse.ArgumentParser()
    parser.add_argument("--quantified_zip", required=True)
    parser.add_argument("--unquantified_zip", required=True)
    parser.add_argument("--n", type=int, default=5)
    parser.add_argument("--out_dir", default="outputs")
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    final_df, unmatched, errors = run_final_from_local_zips(
        quantified_zip=args.quantified_zip,
        unquantified_zip=args.unquantified_zip,
        n=args.n
    )

    out_csv = os.path.join(args.out_dir, "predictions.csv")
    final_df.to_csv(out_csv, index=False)
    print("Wrote:", out_csv)

    if unmatched:
        with open(os.path.join(args.out_dir, "unmatched_quantified.txt"), "w") as f:
            for name in unmatched:
                f.write(str(name) + "\n")

    if errors:
        with open(os.path.join(args.out_dir, "errors.txt"), "w") as f:
            for raw_name, qname, err in errors:
                f.write(f"{raw_name}\t{qname}\t{err}\n")